### ISSUE TITLE
There are multiple cookies with name, 'MUSIC_A_T'

### ISSUE THREAD

**Issue by dlgg-new** [FupengWang/CloudMusicUploadHelper#4]
应该是登录信息方面的问题，打开那个key文件发现是加密的，然后我就没办法了

**Comment by FupengWang** [comment]
请尝试删除`ncm_cloud.key`后重新登录

**Comment by dlgg-new** [comment]
> 请尝试删除`ncm_cloud.key`后重新登录

多次删除之后还是无效果

**Comment by FupengWang** [comment]
请提供详细的错误信息

**Comment by dlgg-new** [comment]
`Traceback (most recent call last):
  File "main.py", line 27, in <module>
    upload_main([input("请输入文件上传路径 >>> ")])
  File "/content/CloudMusicUploadHelper/command/upload.py", line 52, in upload_main
    uploadfile(item)
  File "/content/CloudMusicUploadHelper/command/upload.py", line 97, in uploadfile
    cresult = GetCheckCloudUpload(md5)
  File "/usr/local/lib/python3.7/dist-packages/pyncm/apis/__init__.py", line 36, in wrapper
    rsp = requestFunc(url,plain,method)                        
  File "/usr/local/lib/python3.7/dist-packages/pyncm/apis/__init__.py", line 66, in wrapper
    payload = func(*a,**k)
  File "/usr/local/lib/python3.7/dist-packages/pyncm/apis/__init__.py", line 108, in EapiCryptoRequest
    **GetCurrentSession().cookies,
  File "/usr/local/lib/python3.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.7/dist-packages/requests/cookies.py", line 394, in _find_no_duplicates
    raise CookieConflictError('There are multiple cookies with name, %r' % (name))
requests.cookies.CookieConflictError: There are multiple cookies with name, 'MUSIC_A_T'`

我把upload.py中捕捉异常并等待5s的代码删掉了
